= Floating Point Model Documentation
:toc:
:sectnums:

== B10 Add: Shift

Aharoni et al:

=== Description

This model tests every possible value for a shift between the input operands. The difference between the unbiased input exponents is:

* A value smaller than -(p+4)
* All values in the range [-(p+4), (p+4)]
* A value larger than p+4

Number of tests: 1.5 E 3

Precisions supported: BF_16, FP_16, FP_32, FP_64, FP_128

Operations Supported: Add, Subtract

== Implementation

=== Definitions

`max_exp`:: Maximum exponent value based on precision  
`min_exp`:: Minimum exponent value based on precision  
`a`:: Operand 1  
`b`:: Operand 2  
`a_exp`:: Exponent of operand `a`, generally in `[min_exp, max_exp]`  
`b_exp`:: Exponent of operand `b`, generally in `[min_exp, max_exp]`  
`p`:: Number of significant bits (precision)

=== Background

Description: In order to properly execute floating point addition or subtraction, a processor must align the significands of the operands such that both operands share the same exponent value (Ercegovac, 418). In order to test that shifting is performed correctly, this test generates two vectors such that their difference in exponents is: 1) a value smaller than -(p+4) 2) all values in the range [-(p+4), (p+4)], and 3) a value larger than p+4. Where the variable p is defined as “the number of significant bits (precision)”(IEEE 754).

== General Procedure

In order to achieve the desired shift amounts between a and b, the difference between a_exp and b_exp needs to be equal to the shift amount specified by each respective test. The following test generation procedures follow the general form of first generating a random value a_exp with restrictions based on the shift amount desired. Then, generating the random b_exp with restrictions based on the shift amount desired. Both mantissa and sign bits are randomized.

== Test Procedure

=== Test 1
Objective: A value smaller than -(p+4)  
Operations: Add, Subtract

To cover this test, the inequality:

[source]
----
a_exp - b_exp < -(p + 4)
----

must be satisfied. Given this inequality, the lower bound on a_exp must be min_exp, because we can always find a value larger than min_exp such that their difference is < (p+4). Now, for determining an upper limit of a_exp, we must consider that the largest b_exp and a_exp can be is max_exp. If both a_exp = max_exp and b = max_exp, then their difference = 0. Therefore, we must decrease a_exp by 5 such that:

[source]
----
(max_exp - 5) - max_exp = -5
----

Thus satisfying the inequality at the largest value of a_exp and b_exp. Therefore, the range of a_exp must be:

[source]
----
[min_exp, max_exp - (p+5)]
----

Within this test, a_exp is generated as a random value within the range [min_exp, max_exp - (p+5)].

With a_exp determined, the value b_exp will become restricted in order to satisfy the inequality:

[source]
----
a_exp - b_exp < -(p + 4)
----

Understanding this inequality, b_exp’s upper bound must be max_exp. However, b_exp’s lower bound is restricted by how large a_exp is. We can begin by considering the most extreme case where:

[source]
----
a_exp = max_exp - (p+5)
----

If this is the case, the only value of b_exp to satisfy the test is where:

[source]
----
b_exp = max_exp
----

That means that the possible number of values possible for b_exp = the upper bound of a_exp - the value of a_exp. This can be rewritten as:

[source]
----
possible values of b_exp = (max_exp-(p+5)) - a_exp
----

These possible values must be subtracted from max_exp in order to find the lower bound of b_exp. The range of b_exp = [max_exp - possible b_exp values, max_exp]. b_exp is randomly generated as a value within the range [max_exp - possible b_exp values - max_exp].

---

=== Test 2
Objective: All values within the range [-(p+4), (p+4)]  
Operations: Add/Subtract

To cover this test:

[source]
----
a_exp - b_exp ∈ [-(p+4), (p+4)]
----

In order to satisfy this, we can first look towards generating:

[source]
----
a_exp - b_exp = all values in the range [0, -(p+4)]
----

This will be accomplished by starting with a randomly generated value a_exp, setting:

[source]
----
b_exp = a_exp
----

and then incrementing b_exp by 1 until:

[source]
----
a_exp - b_exp = -(p+4)
----

Using this framework, that means that the value a_exp must have an upper limit such that we can increment over it p+4 times. The upper limit must therefore be:

[source]
----
max_exp - (p+4)
----

Because we are not concerned with decrementing below the value a_exp, the lower limit of a_exp is min_exp. a_exp is a random value generated within the range [min_exp, max_exp - (p+4)].

With a_exp determined, we enter a loop to increment b_exp. On the first iteration, b_exp = a_exp and create a test vector based on this value. After generating this test vector, b_exp is incremented. Looping occurs p+5 times to account for the first case where a_exp = b_exp and to allow for a_exp - b_exp = p+4.

Now, tests such that:

[source]
----
a_exp - b_exp = all values in the range [-(p+4), -1]
----

must be generated. This can be accomplished by determining a value a_exp, setting:

[source]
----
b_exp = a_exp - 1
----

and decrementing the value of b_exp until:

[source]
----
a_exp - b_exp = p+4
----

Because b_exp will be decremented under the value of a_exp, a total of p+4 times, the lower limit of a_exp must be min_exp + p + 4. There is no concern of b_exp or a_exp being incremented, so the upper limit of a_exp is max_exp. a_exp was generated as a random value within the range [min_exp + p + 4, max_exp].

With a_exp determined, we enter a loop to decrement b_exp. On the first iteration, b_exp = a_exp - 1 and create a test vector based on this value. Looping occurs p + 4 times to allow for a final value of a_exp - b_exp = p+4.

---

=== Test 3
Objective: A value larger than p+4  
Operations: Add/Subtract

In order to satisfy this test:

[source]
----
a_exp - b_exp > (p + 4)
----

Within this test, the range for b_exp is the same as the ranges determined by a_exp in test 1 and the range for a_exp is the same as b_exp in test 1. For simplicity, this test is accomplished with the same logic as test 1. However, when generating the test vectors, b_exp and a_exp are swapped.

== Test count Breakdown

[cols="1,1,1,1,1,1",options="header"]
|===
|Precision |p |Test 1 |Test 2 |Test 3 |Total

|BF_16 |8 |1 |25 |1 |27
|FP_16 |11 |1 |31 |1 |33
|FP_32 |24 |1 |57 |1 |59
|FP_64 |53 |1 |115 |1 |117
|FP_128 |113 |1 |235 |1 |237
|===

Total: 473

(Accounting for Add/Sub)

[source]
----
473(2) = 946
----